#!/usr/bin/env bash

# TODO: How to integrate?
source /usr/local/opt/gnu-getopt/etc/bash_completion.d

for bash_comp_script in ~/.bash/completions/*; do
    # shellcheck disable=SC1090
    test -f "${bash_comp_script}" && source "${bash_comp_script}"
done
