#!/bin/sh
# Borrowed from: https://gitlab.com/khaytsus/mxergo

DISPLAY=:0

# Go ahead and make sure xbindkeys is running
#xbindkeys

# USB Unified Receiver for MX Ergo
xinput --set-prop "pointer:Logitech MX Ergo" 'libinput Accel Speed' -.90
xinput --set-prop "pointer:Logitech MX Ergo" 'Coordinate Transformation Matrix' 1 0 0 0 1 0 0 0 .6
xinput --set-prop "pointer:Logitech MX Ergo" 'libinput Natural Scrolling Enabled' 1
