#!/usr/bin/env bash
set -euo pipefail


OSASCRIPT_GET_ALACRITTY_WINDOWS="$(cat <<EOF
tell application "System Events" to set alacritty_windows to get the title of every window of process "Alacritty"

set output to ""
repeat with window_name in alacritty_windows
    set output to output & window_name & linefeed
end repeat

return output
EOF
)"
readonly OSASCRIPT_GET_ALACRITTY_WINDOWS

readonly TMUX_CONFIG_PATH="${HOME}/.config/tmux/tmux.conf"
readonly TMUX_EXEC_PATH='/opt/homebrew/bin/tmux'
readonly TMUX_SESSION_NAME_TPL='alacritty-window-<I>'

function main {
    if ! command -v osascript &> /dev/null; then
        >&2 echo 'Error: Failed to locate osascript utility'
        exit 1
    fi

    # shellcheck disable=SC2009
    if ! ps aux | grep Alacritty | grep -v grep &> /dev/null; then
        >&2 echo 'Error: Alacritty does not seem to be running'
        exit 1
    fi

    # NOTE: May fail on the first run and ask for assistive access permission for a parent process (which would be Alacritty,
    # if used as part of ~/.config/alacritty/alacritty.yml configuration).
    local alacritty_windows
    alacritty_windows="$(osascript -e "${OSASCRIPT_GET_ALACRITTY_WINDOWS}")"

    local alacritty_windows_number
    alacritty_windows_number="$(echo "${alacritty_windows}" | wc -l)"

    local tmux_session_name
    tmux_session_name="${TMUX_SESSION_NAME_TPL/<I>/"${alacritty_windows_number}"}"

    "${TMUX_EXEC_PATH}" -u attach -t "${tmux_session_name}" || \
        "${TMUX_EXEC_PATH}" -u -f "${TMUX_CONFIG_PATH}" new-session -s "${tmux_session_name}"
}

main "$@"
