#!/usr/bin/env bash
#
###############################################################################
# Title:       revpics
# Description: Revise pics in each dir with feh and decide whether to delete
# Usage:       Add to PATH and use it
# Version:     0.0.1
###############################################################################
set -euo pipefail


readonly CURRENT_DIR="$(pwd)"


function main {
    local view_only=false
    if test "$#" -eq 2; then
        if test "$1" = '-v'; then
            shift
            view_only="$1"
        fi
    fi

    if ! test "$view_only" = true && test -f "./.processed"; then
        echo '+ Already processed'
        echo '! Remove ./.processed to override'
        exit 0
    fi

    for file in "${CURRENT_DIR}"/*; do
        # Get a file name and check whether it is a directory
        dir_name="$(basename -- "${file}")"
        if ! test -d "./${dir_name}"; then
            continue
        fi

        # Open the directory contents in feh
        echo "> Reviewing a directory: ${dir_name}"
        if ! test "${view_only}" = true; then
            if test -f "./${dir_name}/.approved"; then
                echo '+ Already reviewed'
                continue
            fi
        fi

        feh -F "./${dir_name}"

        # Check whether the user wishes to delete it
        if ! test "${view_only}" = true; then
            local user_decision
            read -p '??? Delete the folder (Y/n): ' -n 1 -r user_decision
            echo

            if test "${user_decision}" == 'Y'; then
                rm -r "./${dir_name}"
                echo '+ Directory deleted'
            else
                touch "./${dir_name}/.approved"
                echo '+ Marked as approved'
            fi
        fi

        # Block untill user proceeds
        read -p '> Press any key to continue ' -r -n 1
        echo
    done

    # Mark the whole parent dir as processed
    if ! test "${view_only}" = true; then
        local user_decision
        read -p '??? Mark parent as processed (Y/n): ' -n 1 -r user_decision
        echo

        if test "${user_decision}" == 'Y'; then
            touch ./.processed
        fi
    fi

    echo '> DONE!'
}


main "$@"
