#!/usr/bin/env bash
#
###############################################################################
# Title:       lock_screen
# Description: Lock screen using a locker of my choice
# Usage:       Copy to /usr/bin or other only root accessible place in path
#              and bind to a shortcut in the WM.
# Version:     0.0.1
###############################################################################
set -euo pipefail


readonly LOCK_SCREEN_MSG=''
readonly LOCK_SCREEN_FONT='Hack Nerd Font'


###############################################################################
# Main function handling execution pipeline
###############################################################################
function main {
    i3lock-next "${LOCK_SCREEN_MSG}" "${LOCK_SCREEN_FONT}" &
}


###############################################################################
# Main flow
###############################################################################
main
