#!/usr/bin/env bash
#
###############################################################################
# Title:       unpackall
# Description: Unpack all archives in the folder
# Usage:       Add to PATH and use it
# Version:     0.0.1
###############################################################################
set -euo pipefail


readonly CURRENT_DIR="$(pwd)"


function main {
    for file in "${CURRENT_DIR}"/*; do
        local file_name
        local folder_name

        # Get a file name and check whether it is an archive
        file_name="$(basename -- "${file}")"
        if test "${file_name: -4}" != ".zip"; then
            continue
        fi

        # Remove extension and stupid characters
        folder_name="$(
            echo "${file_name%.*}" | \
            tr -cd '[:alnum:] ' | \
            sed -e 's/\s/_/g'
        )"

        echo "> Extracting ./${file_name} to ./${folder_name}"

        mkdir "${folder_name}" && \
            unzip -d "./${folder_name}" "./${file_name}" &> /dev/null && \
            rm "./${file_name}"
    done
}


# FIXME: That supports zip archives only for now
main
