#!/usr/bin/env bash
set -euo pipefail

readonly SHARE_NAME="$(hostname | tr '[:lower:]' '[:upper:]')"
readonly MOUNT_PATH=/mnt/shared

function main {
    if ! hash vmware-hgfsclient vmhgfs-fuse &> /dev/null; then
        echo 'Error: vmware-hgfsclient and vmhgfs-fuse utilities are not installed'
        exit 1
    fi

    if ! test -d "${MOUNT_PATH}"; then
        echo "Error: Mount path does not exist: ${MOUNT_PATH}"
        exit 1
    fi

    if ! vmware-hgfsclient | grep "${SHARE_NAME}" &> /dev/null; then
        echo "Error: VMWare share does not exist: ${SHARE_NAME}"
        exit 1
    fi

    vmhgfs-fuse -o allow_other -o auto_unmount .host:/"${SHARE_NAME}" "${MOUNT_PATH}" &&
        echo "OK: Mounted ${SHARE_NAME} -> ${MOUNT_PATH}" ||
        echo "Error: Failed to mount ${SHARE_NAME} -> ${MOUNT_PATH}"
}

main "$@"
