#!/usr/bin/env bash

# monitor constants
INT=eDP-1
EXT=HDMI-1

# grep monitors
# xrandr | grep -o -P "^eDP.*?\s"


# keep polling xrandr
while true; do
    # using internal monitor but external was connected
    if [ ! "${ACT}" == "${EXT}" ] && xrandr | grep "${EXT} connected"; then
        # setup xrandr to use external monitor only
        xrandr --output "${INT}" --off --output "${EXT}" --auto
        ACT="${EXT}"
    fi

    # using external monitor but it was disconnected
    if [ "${ACT}" == "${EXT}" ] && xrandr | grep "${EXT} disconnected"; then
        # setup xrandr to use internal monitor only
        xrandr --output "${EXT}" --off --output "${INT}" --auto
        ACT="${INT}"
    fi

    # sleep for a moment
    sleep 1
done
